### ISSUE TITLE
Proposed sitemap

### ISSUE THREAD

**Issue by savetheclocktower** [confused-Techie/pulsar-documentation-eleventy#6]
I mentioned before that I think we could consolidate some sections and differentiate them a bit better. Here's what I've got so far, with changes explained in italics. Let me know if this seems OK:

* Getting started
  * What is Pulsar?
  * Installing Pulsar
  * Dependencies for some community packages

* Using Pulsar _(article titles rewritten to remove redundant references to Pulsar)_
  * Basics
  * Movement
  * Packages
  * Selections
  * Editing and deleting text

* Core packages and features _(article titles rewritten to remove redundant references to Pulsar)_
  * Find and replace
  * Snippets
  * Autocomplete
  * Version control
  * GitHub
  * Spell check
  * Previews
  * Folding
  * Panes
  * Grammars

* ~~Customize~~ Customizing Pulsar _(renamed for consistency)_ 
  * Configuring with CSON
  * Creating your own snippets
  * Tweaking styles
  * Customizing keybindings
  * Configuring global settings
  * Configuring language-specific settings
  * Customizing language recognition
  * Controlling where data is stored
  * The init file

* ~~Package guides~~ _(I think this should be a series of articles underneath another heading, most likely Developing for Pulsar)_

* The infrastructure of Pulsar _(formerly “Behind Pulsar”)_
  * Configuration API
  * Keymaps in depth
  * Scoped settings, scopes, and scope descriptors
  * Serialization
  * Developing Node modules
  * Interacting with other packages via services

* Developing for Pulsar
  * ~~Summary~~ _(Should be removed unless we have meaningful content to put on this page)_
  * Creating a community package
  * Package example: Word count
  * Package example: Modifying text
  * Package example: Active editor info
  * Creating a community theme
  * Package example: Syntax theme _(once this guide exists)_
  * Creating a language grammar (overview)
  * Creating a language grammar (Modern Tree-sitter)
  * Creating a language grammar (legacy Tree-sitter) (or omit this altogether)
  * Creating a language grammar (TextMate)
  * _(We don’t need the “converting a grammar from TextMate” docs)_
  * Publishing your package
  * Maintaing your package
  * Using icons
  * Writing specs
  * Handling URIs
  * ~~Contributing to official Pulsar packages~~ _(moved to the “Contributing to Pulsar” section)_

* Troubleshooting Pulsar _(renamed from “Debugging Pulsar”)_
  * Having trouble? _(moved from “FAQ” section)_
  * Common issues _(moved from “FAQ” section)_
  * Update to the latest version
  * Using safe mode
  * Clearing saved state
  * Resetting to factory defaults
  * Checking for linked packages
  * Checking for incompatible packages
  * Checking Pulsar and package configuration
  * Checking your keybindings
  * Diagnosing font rendering issues _(still needed?)_
  * Checking for errors in developer tools
  * Locating crash logs
  * Diagnosing startup performance
  * Profiling startup performance
  * Diagnosing runtime performance
  * Checking your build tools
  * Checking if your GPU is causing the problem

* FAQ _(contents moved to the ”Troubleshooting Pulsar” section)_

* ~~Hacking pulsar~~ Contributing to Pulsar _(to contrast it with “Customizing Pulsar”)_
  * Building Pulsar
  * Using PPM
  * Hacking on the core
  * Tools of the trade
  * Contributing to official Pulsar packages _(moved from the “Developing for Pulsar” section)_

* The Pulsar organization _(formerly “Maintaining Pulsar”)_ — _(actually, we should also ask ourselves whether this needs to be included at all)_
  * Tooling

**Comment by confused-Techie** [comment]
Overall totally love these changes, and think they make total sense.

Although on the few items being proposed for removal (textmate conversion and legacy Tree-sitter) I'd argue it's still important to keep those around up until their functionality is actually removed. But of course we can add big warnings to not to anything new with this information, but keep it around for understanding and troubleshooting legacy content.

But otherwise this looks totally fantastic! The only idea I've had otherwise is instead of "The infrastructure of Pulsar" being "Pulsar in-depth" but that's naming only and not super important

**Comment by savetheclocktower** [comment]
> But otherwise this looks totally fantastic! The only idea I've had otherwise is instead of "The infrastructure of Pulsar" being "Pulsar in-depth" but that's naming only and not super important

I don't love either of these names, to be honest, so I'll keep brainstorming. I want to make sure people know how that section is different from others.

**Comment by confused-Techie** [comment]
Yeah that's valid, but otherwise this does sound awesome to me. So I'll hold off fixing all the links until we get slugs finalized

**Comment by savetheclocktower** [comment]
OK, gonna open another PR soon once I move everything around. I'll keep thinking about a better name for that one section
